### ISSUE TITLE
Add ability to use personal access token

### ISSUE THREAD

**Issue by jeffbyrnes** [nicklayb/alfred-bitbucket#25]
Our company Bitbucket install doesn’t allow the creation of oAuth apps, but it will all personal access tokens to be generated.

Any interest?

**Comment by nicklayb** [comment]
I'm interested in supporting as most case as possible. But I don't find those in my bitbucket settings. I also noticed that the settings have a bit changed since I wrote the README.

If you can point me to where you configure those I'll have a look. But if I remember well, the use of Oauth is per-account, not per team. I'm actually surprised that you cannot do it.

**Comment by jeffbyrnes** [comment]
@nicklayb I suspect they disabled it 🤷‍♂️ 

It’s located at Manage Account → Personal Access Token. Ours is a self-hosted, on-premise version, Bitbucket Server. Here’s the [docs on Personal Access Tokens](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html).

Now I see that’s no longer a thing at bitbucket.org?

And it looks like the oAuth stuff for bitbucket.org is now located at https://bitbucket.org/$workspace_name/workspace/settings/api

**Comment by LordZardeck** [comment]
@nicklayb I've added support for app passwords in #27 if you want to review and merge. This was needed for me as well, as my company doesn't allow access to OAuth apps.

**Comment by LordZardeck** [comment]
@jeffbyrnes #27 Got merged in so now you should be able to use it with App Passwords. @nicklayb This issue should be closed out now.

**Comment by nicklayb** [comment]
I didn't pushed any new version yet, I will fix dependabots issues before

**Comment by LordZardeck** [comment]
I believe this will also address #26 too

**Comment by nicklayb** [comment]
Version 1.5.1 should fix this
